// <auto-generated />
using System;
using FlightSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightSystem.Data.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20241001165540_more seed data 2")]
    partial class moreseeddata2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FlightSystem.Data.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46abd40f-ea2c-44fe-b097-0d02ed1cfc1b"),
                            Code = "ATL",
                            Name = "Atlanta"
                        },
                        new
                        {
                            Id = new Guid("ad73e0c5-6334-40e7-8e33-55cc5991a967"),
                            Code = "EWR",
                            Name = "Newark"
                        },
                        new
                        {
                            Id = new Guid("d8943187-a9eb-44e1-b5ec-60d6184f97b1"),
                            Code = "SLC",
                            Name = "Salt Lake City"
                        },
                        new
                        {
                            Id = new Guid("3df2f443-3c88-43f3-a5da-feef551349d4"),
                            Code = "PHI",
                            Name = "Philadelphia"
                        });
                });

            modelBuilder.Entity("FlightSystem.Data.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcdab3b7-bde5-4afc-bf95-d2b4291000e7"),
                            Departure = new DateTime(2024, 10, 1, 12, 55, 40, 122, DateTimeKind.Local).AddTicks(6841),
                            DestinationId = new Guid("46abd40f-ea2c-44fe-b097-0d02ed1cfc1b"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            OriginId = new Guid("ad73e0c5-6334-40e7-8e33-55cc5991a967")
                        });
                });

            modelBuilder.Entity("FlightSystem.Data.Flight", b =>
                {
                    b.HasOne("FlightSystem.Data.Airport", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightSystem.Data.Airport", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });
#pragma warning restore 612, 618
        }
    }
}
